version: '3.8'

services:
 factorio-server:
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
      - "25565:25565"
    volumes:
      - factorio:/opt/factorio
      - ./test:/factorio_headless/test
      - ./saves:/opt/factorio/saves
      - ./data:/opt/factorio/data
      - ./config:/opt/factorio/config/
    # command:
      # /bin/tar -xf /factorio_headless/factorio_headless.tar.gz -C /factorio_headless/test
    #  tail -F /bin/sh

    # environment:
    #   - SAVE_FILE:init.zip
      # - ENV_VAR=value

volumes:
  factorio: