version: '3.8'

services:
 factorio-server:
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
      - "25565:25565"
    volumes:
      - factorio:/opt/factorio
    # command: tail -F /bin/sh

    # environment:
    #   - SAVE_FILE:init.zip
      # - ENV_VAR=value

volumes:
  factorio: